services:
  - type: web
    name: whatsapp-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /status
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: AUTH_DIR
        value: ./auth_info
      - key: ADMIN_JID
        value: 966595510125@s.whatsapp.net
      - key: PORT
        value: 3000
      - key: RENDER_URL
        value: https://whatsapp-bot-1cxj.onrender.com
      - key: ADMIN_PASSWORD
        sync: false
